name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug, wait for review]
body:
  - type: textarea
    attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
    validations:
      required: false
