package org.jkiss.dbeaver.ext.altibase.model;

import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
import org.jkiss.dbeaver.model.DBPNamedObject2;
import org.jkiss.dbeaver.model.meta.Property;

public class AltibaseTableColumn extends GenericTableColumn implements DBPNamedObject2 { //, DBSTypedObjectExt4<AltibaseDataType> {

	public AltibaseTableColumn(GenericTableBase table) {
		super(table);
	}

	public AltibaseTableColumn(
			GenericTableBase table,
			String columnName,
			String typeName,
			int valueType,
			int sourceType,
			int ordinalPosition,
			long columnSize,
			long charLength,
			Integer scale,
			Integer precision,
			int radix,
			boolean notNull,
			String remarks,
			String defaultValue,
			boolean autoIncrement,
			boolean autoGenerated)
	{
		super(table,
				columnName,
				typeName,
				valueType,
				sourceType,
				ordinalPosition,
				columnSize,
				charLength,
				scale,
				precision,
				radix,
				notNull,
				remarks,
				defaultValue,
				autoIncrement,
				autoGenerated);
	}

	/*
	 * No auto-generated or auto-increment table columns in Altibase
	 */
	@Override
    @Property(viewable = false, order = 51)
    public boolean isAutoGenerated()
    {
        return autoGenerated;
    }

    @Override
    @Property(viewable = false, hidden = true, order = 52)
    public boolean isAutoIncrement()
    {
        return super.isAutoIncrement();
    }
}
